In [1]:
import sys
sys.path.append(r'D:\PyCharmProjects\VFPUGEN')
sys.path.append(r'/root/VFPUGEN')
sys.path.append(r'D:\PycharmProjects\VFPUGEN')
%load_ext autoreload
%autoreload 2

%matplotlib inline

In [3]:
import pandas as pd
import os
from consts.Constants import DATASETS_PATH

In [4]:
df = pd.read_csv(os.path.join(DATASETS_PATH, 'bank_coded_onehot.csv'))

In [5]:
df

,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,...,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,0,0,0,1,0,0,0,0,0,0,...,0.010471,-0.565922,0.195414,-0.349494,0.648092,0.722722,0.886447,0.712460,0.331680,0
1,0,0,0,0,0,0,0,1,0,0,...,-0.421501,-0.565922,0.195414,-0.349494,0.648092,0.722722,0.886447,0.712460,0.331680,0
2,0,0,0,0,0,0,0,1,0,0,...,-0.124520,-0.565922,0.195414,-0.349494,0.648092,0.722722,0.886447,0.712460,0.331680,0
3,1,0,0,0,0,0,0,0,0,0,...,-0.413787,-0.565922,0.195414,-0.349494,0.648092,0.722722,0.886447,0.712460,0.331680,0
4,0,0,0,0,0,0,0,1,0,0,...,0.187888,-0.565922,0.195414,-0.349494,0.648092,0.722722,0.886447,0.712460,0.331680,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,0,0,0,0,0,1,0,0,0,0,...,0.292025,-0.565922,0.195414,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697,1
41184,0,1,0,0,0,0,0,0,0,0,...,0.481012,-0.565922,0.195414,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697,0
41185,0,0,0,0,0,1,0,0,0,0,...,-0.267225,-0.204909,0.195414,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697,0
41186,0,0,0,0,0,0,0,0,0,1,...,0.708569,-0.565922,0.195414,-0.349494,-0.752343,2.058168,-2.224953,-1.495186,-2.815697,1
41187,0,0,0,0,0,1,0,0,0,0,...,-0.074380,0.156105,0.195414,1.671136,-0.752343,2.058168,-2.224953,-1.495186,-2.815697,0